name: CarOfTheYear.Ph
favicon: null
layout_spectrum: 0.61078
typography_spectrum: 0.87572
title: WWW.Car of the Year.Ph
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#e92728'
    - '#6c6c6c'
    - '#a0a0a0'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
