name: CarOfTheYearPh
favicon: null
layout_spectrum: 0.61078
typography_spectrum: 0.87572
title: Car of the Year - Philippines
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c9904a'
    - '#533612'
    - '#a60000'
    - '#646464'
  brandStrength: 0.125
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
